############################Stages##########################################
stages:
  - auto-deploy

###########################TEMPLATE#########################################

.template-deploy:
  stage: auto-deploy
  tags:
    - devops
  script:
    - mkdir deploy
    - git clone https://github.com/sulaimantok/Automation-Deployment-Github
    - cd apicrud-restapi/
    - mvn clean install
    - eval $(minikube -p kube.api docker-env) && docker build -t api-service .
    - kubectl apply -f kubernetes/mysql/
    - kubectl apply -f kubernetes/app/
  after_script:
    - cd ../../
    - rm deploy

#################################JOBS################################

auto-deploy-jobs:
  extends: .template-deploy
  when: manual
  only:
    refs:
      - web
